version: "3.9"
services:
  backend:
    restart: always
    container_name: api
    command : bash -c "python manage.py migrate &&
     python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
  frontend:
    restart: always
    command : npm start
    container_name: app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    stdin_open: true
