# Generated by Django 4.1.6 on 2023-02-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.TextField()),
                ("variable", models.TextField()),
                ("time_of_occurrence", models.DateTimeField()),
                ("alarming_fact", models.TextField()),
                (
                    "alarm_preview",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("type", models.TextField()),
                ("severity", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("cleared", "Cleared"),
                        ],
                        max_length=12,
                    ),
                ),
                ("originator", models.TextField()),
                ("created_time", models.DateTimeField()),
                ("acknowledged_time", models.DateTimeField(blank=True, null=True)),
                ("cleared_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParamSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paramset_name", models.TextField()),
                ("paramset_value", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActiveSignalCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.TextField()),
                (
                    "variable_name",
                    models.CharField(
                        choices=[
                            ("water_level", "Water Level"),
                            ("battery_voltage", "Battery Voltage"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "check_name",
                    models.CharField(
                        choices=[
                            ("last_datapoint", "Last Datapoint"),
                            ("battery_level", "Battery Level"),
                            ("prs_qos", "Prs Qos"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "param_set",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alerting.paramset",
                    ),
                ),
            ],
        ),
    ]
