# Generated by Django 4.1.6 on 2023-02-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activesignalcheck",
            name="check_name",
            field=models.CharField(
                choices=[
                    ("last_data", "Last Datapoint"),
                    ("battery_level", "Battery Level"),
                    ("prs_qos", "Prs Qos"),
                ],
                max_length=14,
            ),
        ),
    ]
