# Generated by Django 4.1.6 on 2023-03-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerting", "0002_alter_activesignalcheck_check_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activesignalcheck",
            name="variable_name",
            field=models.CharField(
                choices=[
                    ("water_level", "Water Level"),
                    ("battery_voltage", "Battery Voltage"),
                    ("pressure", "Pressure"),
                    ("inductive_conductivity", "Inductive Conductivity"),
                    ("dielectric_permittivity", "Dielectric Permittivity"),
                    ("ambient_air_temperature", "Ambient Air Temperature"),
                    ("headspace_temperature", "Headspace Temperature"),
                    ("water_temperature", "Water Temperature"),
                    ("soil_temperature", "Soil Temperature"),
                    ("flow_rate", "Flow Rate"),
                    ("rainfall_intensity", "Rainfall Intensity"),
                ],
                max_length=23,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="variable",
            field=models.CharField(
                choices=[
                    ("water_level", "Water Level"),
                    ("battery_voltage", "Battery Voltage"),
                    ("pressure", "Pressure"),
                    ("inductive_conductivity", "Inductive Conductivity"),
                    ("dielectric_permittivity", "Dielectric Permittivity"),
                    ("ambient_air_temperature", "Ambient Air Temperature"),
                    ("headspace_temperature", "Headspace Temperature"),
                    ("water_temperature", "Water Temperature"),
                    ("soil_temperature", "Soil Temperature"),
                    ("flow_rate", "Flow Rate"),
                    ("rainfall_intensity", "Rainfall Intensity"),
                ],
                max_length=23,
            ),
        ),
    ]
