# Generated by Django 4.1.6 on 2023-03-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerting", "0003_alter_activesignalcheck_variable_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activesignalcheck",
            name="check_name",
            field=models.CharField(
                choices=[
                    ("last_data", "Last Datapoint"),
                    ("battery_level", "Battery Level"),
                    ("prs_qos", "Prs Qos"),
                    ("rain_sum", "Rain Sum"),
                ],
                max_length=14,
            ),
        ),
    ]
